import numpy as np
from matplotlib import pyplot as plt


i = np.load("exc_perturbs/optim.npy")  # .mean(2)
e = np.load("inh_perturbs/optim.npy")  # .mean(2)
diff = (e - i).mean(2).squeeze()
# diff = (((e-e.mean(2, keepdims=True)) / e.std(2, keepdims=True)) - ((i-i.mean(2, keepdims=True)) / i.std(2, keepdims=True))).mean(2).squeeze()
i = i.mean(2)
e = e.mean(2)
# i = (i - i.mean()) / i.std()
# e = (e - e.mean()) / e.std()
# diff = (e - i).squeeze()
diff_max = max(diff.max(), -diff.min())
i_max = max(i.max(), -i.min())
e_max = max(e.max(), -e.min())

f = plt.figure()
plt.subplot(131);plt.title("Inhibition");plt.imshow(-i.squeeze(), cmap="RdBu_r", vmax=i_max, vmin=-i_max)
plt.subplot(132);plt.title("Excitation");plt.imshow(e.squeeze(), cmap="RdBu_r", vmax=e_max, vmin=-e_max)
plt.subplot(133);plt.title("E - I");plt.imshow(diff, vmin=-diff_max, vmax=diff_max, cmap="RdBu_r");plt.colorbar();plt.show()
plt.close(f)

f, ax = plt.subplots(1, 1)
i_curves = np.load("inh_perturbs/curves.npy").squeeze()
e_curves = np.load("exc_perturbs/curves.npy").squeeze()
inh_labels = np.load("inh_perturbs/label.npy").squeeze()
exc_labels = np.load("exc_perturbs/label.npy").squeeze()
[plt.plot(i_curves[i], label="{}".format(i)) for i in range(i_curves.shape[0])]
plt.title("Inh perturb recovery over epochs of optim")
plt.plot(inh_labels, "k--", label="Target")
plt.legend()
plt.ylabel("Neural response")
plt.xlabel("Orientation")
ax.set_xticks([0, 1, 2, 3, 4, 5])
ax.set_xticklabels([-90, -60, -30, 0, 30, 60])
plt.show()
plt.close(f)
f, ax = plt.subplots(1, 1)
[plt.plot(e_curves[i], label="{}".format(i)) for i in range(e_curves.shape[0])]
plt.title("Exc perturb recovery over epochs of optim")
plt.plot(exc_labels, "k--", label="Target")
plt.legend()
plt.ylabel("Neural response")
plt.xlabel("Orientation")
ax.set_xticks([0, 1, 2, 3, 4, 5])
ax.set_xticklabels([-90, -60, -30, 0, 30, 60])
plt.show()
plt.close(f)

f = plt.figure()
plt.title("Functional connectivity of BSDS-trained $\gamma$-net (fGRU-0)")
plt.imshow(diff, vmin=-diff_max, vmax=diff_max, cmap="RdBu_r")
plt.axis("off")
co = plt.colorbar()
co.set_label("(-) Inhibition                  Excitation (+)")
plt.show()
plt.close(f)

